# mkdocs.yml

site_name: CodeBlue WP4
site_url: https://acapet.github.io/CodeBlueWP4/
theme:
  name: mkdocs

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
nav:
  - Home: index.md
  - Annual indicators : indicators.md
  - Monthly layers: monthly_layers.md
  - Daily layers: daily_layers.md
  - Stations: stations.md
  - Validation tables : validation_tables.md
